/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyectofinalresto.AccesoVista;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectofinalresto.AccesoAInformacion.AccesoMesa;
import proyectofinalresto.AccesoAInformacion.AccesoMesero;
import proyectofinalresto.AccesoAInformacion.AccesoPedido;
import proyectofinalresto.AccesoAInformacion.AccesoProducto;
import proyectofinalresto.Entidades.Mesa;
import proyectofinalresto.Entidades.Mesero;
import proyectofinalresto.Entidades.Pedido;
import proyectofinalresto.Entidades.Producto;

/**
 *
 * @author ayala
 */
public class GenerarPedido extends javax.swing.JInternalFrame {
    DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form GenerarPedido
     */
    public GenerarPedido() {
        initComponents();
        llenarComboBoxMesero(); 
        edittable();
        llenarComboBoxProducto();
        llenarComboBoxMesa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        comboBoxProducto = new javax.swing.JComboBox<>();
        comboBoxMesero = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jComboMesa = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir_1.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        comboBoxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxProductoActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Entregado", "Cancelado" }));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tablaProductos.setBackground(new java.awt.Color(153, 153, 255));
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/resto.png"))); // NOI18N
        jLabel1.setText("RESTO EXQUISITO");

        jButton3.setText("Borrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Deshacer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("Eliminar pedido cancelado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel1)))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(comboBoxMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jComboMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(comboBoxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addGap(82, 82, 82)
                                .addComponent(jButton1)
                                .addGap(82, 82, 82)
                                .addComponent(jButton3)
                                .addGap(65, 65, 65))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jButton2)))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxMesero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3)
                            .addComponent(jButton4))))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxProductoActionPerformed
      Producto producto = (Producto)comboBoxProducto.getSelectedItem();
      AccesoProducto accesoProducto = new AccesoProducto();
      List<Producto>productos = accesoProducto.obtenerProducto(producto.getIdProducto());
      if(producto != null){
       model.addRow(new Object[]{
           producto.getIdProducto(),
           producto.getNombreProducto(),
           producto.getCantidad(),
           producto.getPrecio()
     
       }); 
               }
    }//GEN-LAST:event_comboBoxProductoActionPerformed
    // LOGICA GUARDAR PEDIDO    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            Mesa mesa = (Mesa) jComboMesa.getSelectedItem();
            Mesero mesero = (Mesero) comboBoxMesero.getSelectedItem();
            String estado1 = (String) jComboBox3.getSelectedItem();

            if (mesa != null && mesero != null && estado1 != null) {
                int rowCount = tablaProductos.getRowCount();
                AccesoProducto accesoPro = new AccesoProducto();
                List<Producto> listaDeProductos = accesoPro.ListaDeProducto();

                for (int i = 0; i < rowCount; i++) {
                    int idProduct = (Integer) model.getValueAt(i, 0);

                    Producto productoSeleccionado = null;
                    for (Producto producto : listaDeProductos) {
                        if (producto.getIdProducto() == idProduct) {
                            productoSeleccionado = producto;
                            Pedido nuevoPedido = new Pedido(mesa, mesero, productoSeleccionado, estado1);
                            AccesoPedido accesoPedido = new AccesoPedido();
                            accesoPedido.nuevoPedido(nuevoPedido);

                        }
                    }

                }
                model.setRowCount(0);
                JOptionPane.showMessageDialog(this, "Pedido Realizado exitosamente!");
            } else {
                JOptionPane.showMessageDialog(this, "Faltan elementos por seleccionar.");
            }

        } catch (NullPointerException np) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int filaSeleccionada = tablaProductos.getSelectedRow();
        if (filaSeleccionada != -1) {
            DefaultTableModel model = (DefaultTableModel) tablaProductos.getModel();
            model.removeRow(filaSeleccionada);
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccioando ninguna elemento a remover");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try{
       
            Mesa mesa = (Mesa) jComboMesa.getSelectedItem();
            Mesero mesero = (Mesero) comboBoxMesero.getSelectedItem();
            Producto producto = (Producto) comboBoxProducto.getSelectedItem();
            if (mesa != null && mesero != null && producto != null){
                int idmesa = mesa.getIdMesa();
                int idmesero = mesero.getIdMesero();
                int idproducto = producto.getIdProducto();
           AccesoPedido accesopedido = new AccesoPedido();
         accesopedido.borrarPedido(idmesa, idmesero, idproducto);
         model.setRowCount(0);
            }else{
            JOptionPane.showMessageDialog(this, "Falta elementos por seleccionar");
            }
       }catch(NumberFormatException np){
           JOptionPane.showMessageDialog(this, "Datos seleccionados no corresponde al ningun pedido");
       }
    }//GEN-LAST:event_jButton4ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Mesero> comboBoxMesero;
    private javax.swing.JComboBox<Producto> comboBoxProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<Mesa> jComboMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables

private void llenarComboBoxMesero(){
      
    AccesoMesero accesoMesero = new AccesoMesero();
    List<Mesero> listaMesero = accesoMesero.listarMesero();
     comboBoxMesero.addItem(null);
    for(Mesero mesero: listaMesero){
    comboBoxMesero.addItem(mesero);
    }
    }


private void llenarComboBoxMesa(){
      
    AccesoMesa accesoMesa = new AccesoMesa();
    List<Mesa> listaMesa = accesoMesa.ListarMesa();
      jComboMesa.addItem(null);
    for(Mesa mesa: listaMesa){
    jComboMesa.addItem(mesa);
    }
    }

private void llenarComboBoxProducto(){
      
    AccesoProducto accesoproducto = new AccesoProducto();
    List<Producto> listaproductos = accesoproducto.ListaDeProducto();
      comboBoxProducto.addItem(null);
    for(Producto producto: listaproductos){
    comboBoxProducto.addItem(producto);
    }
    }


private void edittable(){
    model.addColumn("-");
    model.addColumn("Nombre");
    model.addColumn("Stock");
    model.addColumn("Precio");
    tablaProductos.setModel(model);
}

}
