/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyectofinalresto.AccesoVista;

import javax.swing.JOptionPane;
import proyectofinalresto.AccesoAInformacion.AccesoMesero;
import proyectofinalresto.Entidades.Mesero;

/**
 *
 * @author ayala
 */
public class LoginMeseroModificarPedido extends javax.swing.JInternalFrame {

    /**
     * Creates new form LoginMeseroModificarPedido
     */
    public LoginMeseroModificarPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritoriologin = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextdni = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        escritoriologin.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("Panel exclusivo para personal de servicio");

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel2.setText("Panel de Gestiones RESTO EXQUISITO");

        jLabel3.setText("Identifiquese con su Documento: ");

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        escritoriologin.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritoriologin.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritoriologin.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritoriologin.setLayer(jTextdni, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritoriologin.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritoriologinLayout = new javax.swing.GroupLayout(escritoriologin);
        escritoriologin.setLayout(escritoriologinLayout);
        escritoriologinLayout.setHorizontalGroup(
            escritoriologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritoriologinLayout.createSequentialGroup()
                .addGroup(escritoriologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritoriologinLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1))
                    .addGroup(escritoriologinLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel2))
                    .addGroup(escritoriologinLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(escritoriologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jTextdni, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        escritoriologinLayout.setVerticalGroup(
            escritoriologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritoriologinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addGroup(escritoriologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritoriologin, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritoriologin, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        String campoDni = jTextdni.getText();
        
        if(!(campoDni.equals(""))){
            int dniMese = Integer.parseInt(campoDni);
            AccesoMesero meseroData = new AccesoMesero();
           Mesero resultado = meseroData.buscarMeseroPorDni(dniMese);
           
           if(resultado != null){
            escritoriologin.removeAll();
            escritoriologin.repaint();
            AccesPermitidoModificarPedido acceso = new AccesPermitidoModificarPedido();
            acceso.setVisible(true);
            escritoriologin.add(acceso);
            escritoriologin.moveToFront(acceso);
           }else{
           JOptionPane.showMessageDialog(this, "Dni ingresado no corresponde a ningun personal de servicio");
           jTextdni.setText("");
           }
        }else{
            JOptionPane.showMessageDialog(this,  "El campo no puede ir vacio!");
        }
        }catch(NumberFormatException nf){
        JOptionPane.showMessageDialog(this, "El campo lleva solo numeros!");
        jTextdni.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritoriologin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextdni;
    // End of variables declaration//GEN-END:variables
}
